### ISSUE TITLE
views: rate limiting

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oaiserver#105]
Currently the OAIServer has no rate limiting feature since the views are installed on the UI application instead of the API application.

Possible solutions:
- Move blueprint to API app (and break ``/oai2d`` URL from Invenio).
- Install Flask-Limiter locally on OAIServer to rate limit only the OAIServer.
- Install Flask-Limiter globally on UI app to rate limit UI app as well.
- ...

**Comment by jirikuncar** [comment]
> Install Flask-Limiter globally on UI app to rate limit UI app as well.

👍

**Comment by lnielsen** [comment]
I'll close the ticket here as I think we can probably just apply the default rate limit on UI app to OAIServer. However before closing, I'm not sure which module would be the best host. Like we have Invenio-REST we could create a new module Invenio-UI or perhaps repurpose Invenio-REST? Then this module could also take care of setting security related headers:

- Content Security Policy
- Subresource Integrity
- X-Content-Type-Options
- X-Frame-Options
- X-XSS-Protection

(right now we're scoring a D on https://observatory.mozilla.org/)

**Comment by jirikuncar** [comment]
The fastest way would be Invenio-Base. Or we can create Invenio-UI and extend Invenio-REST, but I'm afraid of duplicating code.

**Comment by lnielsen** [comment]
Closed in favour of inveniosoftware/invenio-app#7
