### ISSUE TITLE
global: filter out weird characters in set name

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-oaiserver#153]
OAI Sets which contain weird characters in their names cannot be rendered in XML outputs, causing issues with the `ListSets` verb (e.g. `u'para\x0bla'`).

A solution would be to integrate some kind of sanitization like the one applied in [`invenio_records_rest.schemas.fields.SanitizedUnicode`](https://github.com/inveniosoftware/invenio-records-rest/blob/3d63611e7e85ee5a981ff1faa67d11bc166bdfbe/invenio_records_rest/schemas/fields/sanitizedunicode.py#L21-L44).

**Comment by diegodelemos** [comment]
Closed by https://github.com/inveniosoftware/invenio-oaiserver/pull/155.
