### ISSUE TITLE
tests: build error 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oaiserver#163]
https://travis-ci.org/inveniosoftware/invenio-oaiserver/jobs/530784093

Seems related to recent Werkzeug release and that recent Werkzeug releases is only compatible with new Flask releases. Can probably be fixed be specifying minimal version of Werkzeug (the one from flask 0.11) to ensure that old Flask is installed with old Werkzeug, and new Flask with new Werkzeug.

**Comment by slint** [comment]
Closed via #164
