### ISSUE TITLE
query: use ES scroll feature

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-oaiserver#17]
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html
- http://elasticsearch-py.readthedocs.org/en/master/api.html?highlight=scroll#elasticsearch.Elasticsearch.scroll

**Comment by lnielsen** [comment]
Related to inveniosoftware/invenio-records-rest#29

Any ideas for the API implementation?

**Comment by jirikuncar** [comment]
@lnielsen in OAI-PMH we have `resumptionToken` hence the implementation is straightforward. I'm not sure about how to do it nicely in `invenio-search/invenio-records-rest`.
