### ISSUE TITLE
How do you define a basic oai_dc mapping and make records appear?

### ISSUE THREAD

**Issue by axfelix** [inveniosoftware/invenio-oaiserver#177]
Hi,

This module appears to lack any kind of quick start guide that I can see -- it appears to be included with a stock Invenio deployment so the Installation documentation (https://invenio-oaiserver.readthedocs.io/en/latest/installation.html) isn't necessary, but it's not clear how you go from populating an Invenio instance to making records appear with a basic `ListRecords` call, even though the stock configuration appears to include an `oai_dc` metadataPrefix. There's no stock Dublin Core crosswalk that I can see anywhere. Am I missing something? Thanks!

**Comment by axfelix** [comment]
@diegodelemos @lnielsen any help with this? Sorry if this is the wrong place to open the issue.

**Comment by lnielsen** [comment]
The key configuration you have to set is [this one](https://github.com/inveniosoftware/invenio-oaiserver/blob/master/invenio_oaiserver/config.py#L66-L87).

See a full example from [Zenodo](https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L1093-L1169)

**Comment by axfelix** [comment]
Thanks!
