### ISSUE TITLE
Versions conflict invenio-i18n with invenio 3.2.1

### ISSUE THREAD

**Issue by rerowep** [inveniosoftware/invenio-oaiserver#184]
It is not possible to use version 1.2 with invenio 3.2.1. because there is an versions conflict for invenio-i18n.

Requirements for invenio-oaiserver 1.2 -> [invenio-i18n>=1.2.0](https://github.com/inveniosoftware/invenio-oaiserver/blob/5fcba05361378bdeb0315c628f90616ce6eb6b59/setup.py#L89)
Requirements for invenio 3.2.1  -> [invenio-i18n>=1.1.1,<1.2.0](https://github.com/inveniosoftware/invenio/blob/dc73257168c2472a08001a8092d5da412f90dc13/setup.py#L114)

**Comment by lnielsen** [comment]
Invenio v3.2.x supports 
- Invenio-OAIServer v1.1.x
- Invenio-I18N v1.1.x.

Invenio-OAIServer v1.2.x is not supported by v3.2. however, it will be included in the upcoming v3.3 release.

**Comment by ppanero** [comment]
Hi @jma,

Invenio v3.3 (Coming soon) will support:

- Invenio-i18n v1.2.x
- Invenio-OAIServer v1.2.x

The bundles are currently being set [here](https://github.com/inveniosoftware/invenio/pull/4013/files)
