### ISSUE TITLE
Error when creating a set with a search pattern

### ISSUE THREAD

**Issue by sebdeleze** [inveniosoftware/invenio-oaiserver#191]
invenio: 3.4
invenio-oaiserver: 1.2.0

## Describe the bug
An error is thrown when trying to create a OAI-PMH set with a search pattern. The error happens when the application have more than one index in elasticsearch.

In `_new_percolator` function, it loops over all indices and try to create the percolator for all items, and not only for the desired index.

## Expected behavior
The percolator must be created only for index specified in `OAISERVER_RECORD_INDEX` configuration.

**Comment by sebastiendeleze** [comment]
Any news?
