### ISSUE TITLE
global: make base functionalities configurable

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-oaiserver#198]
In order to be able to use the module in InvenioRDM, some core parts have to be made configurable (so that we can keep the original implementation, but still be able to plug-in RDM-specific logic). The configurable parts should be exposed as properties of the `current_oaiserver` proxy.

- [x] `OAISERVER_SEARCH_CLS`: #194
- [x] `OAISERVER_ID_FETCHER`: OAI ID Fetcher (`current_oaiserver.oaiid_fecher`)
- [x] `OAISERVER_RECORD_SETS_FETCHER`: Generating sets for `GetRecord`, `ListIdentifiers`, and `ListRecords`
- [x] `OAISERVER_LAST_UPDATE_KEY`: By default `"_updated"`, for RDM it's just `"updated"`
- [x] `OAISERVER_RECORD_CLS`: By default `'invenio_records.api.Record'`
- [x] `OAISERVER_CREATED_KEY`: Byt default `"_created"`

**Comment by rekt-hard** [comment]
Implemented in #197
