### ISSUE TITLE
settings: fix view and templates

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-oaiserver#2]
- [ ] missing licenses in templates
- [ ] remove usage of old model (record <-> set)
- [ ] add tests
- [ ] check integration with Invenio-Theme

--
please base new work on top of #1

**Comment by jirikuncar** [comment]
@lnielsen do we want people to create OAI sets themself? Shall admin interface be sufficient?

**Comment by lnielsen** [comment]
IMHO admin interface is sufficient - especially since it can have a big performance impact to allow people to create and remove set.
