### ISSUE TITLE
response: identify verb - support for oai-identifier/eprints/friends description tags

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oaiserver#32]
See http://www.openarchives.org/OAI/openarchivesprotocol.html#Identify

It is currently not possible to supply an optional **description** element to the identity method (example provided in above link). Below is an example of the output from Zenodo on  https://zenodo.org/oai2d?verb=Identify:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="/static/xsl/oai2.v1.0.xsl"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2017-11-16T21:50:51Z</responseDate>
  <request verb="Identify">https://zenodo.org/oai2d</request>
  <Identify>
    <repositoryName>Zenodo</repositoryName>
    <baseURL>https://zenodo.org/oai2d</baseURL>
    <protocolVersion>2.0</protocolVersion>
    <adminEmail>info@zenodo.org</adminEmail>
    <earliestDatestamp>2013-05-06T23:27:15Z</earliestDatestamp>
    <deletedRecord>no</deletedRecord>
    <granularity>YYYY-MM-DDThh:mm:ssZ</granularity>
  </Identify>
</OAI-PMH>
```

**Comment by dinosk** [comment]
I see that we have the description element in https://github.com/inveniosoftware/invenio-oaiserver/blob/master/invenio_oaiserver/response.py#L154 but there is no `OAISERVER_DESCRIPTIONS` defined in the config.py. Do we just hard code what we want in the xml in a config variable?

**Comment by lnielsen** [comment]
Let's discuss IRL tomorrow.

**Comment by dinosk** [comment]
Note: there is a test case where there is a sample [friends](https://github.com/inveniosoftware/invenio-oaiserver/blob/master/tests/test_verbs.py#L76) definition and there is an implementation [guide](http://www.openarchives.org/OAI/2.0/guidelines.htm) (#3.1) where they also link the schemas for the fields.
